name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          build-root-directory: app

      - name: Run Checkstyle
        working-directory: app
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        working-directory: app
        run: ./gradlew test

      - name: Generate code coverage report
        working-directory: app
        run: ./gradlew jacocoTestReport

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
