name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Change directory to app
        run: cd app

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        run: ./gradlew test
