name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          build-root-directory: app

      - name: Run Checkstyle
        working-directory: app
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run tests
        working-directory: app
        run: ./gradlew test

      - name: Run Make Report
        working-directory: app
        run: make report

      - name: Run tests and generate coverage
        working-directory: app
        run: |
          ./gradlew test jacocoTestReport

      - name: Upload coverage to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        working-directory: app
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml -t jacoco
          ./cc-test-reporter upload-coverage
